# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TekDT.SEZOY
PackageVersion: 0.2.0.6-beta
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn /norestart
  SilentWithProgress: /qb /norestart
  Interactive: /qb+ /norestart
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/tekdt/sezoybin/releases/download/v0.2.0.6-beta/SEZOY_beta.msi
  InstallerSha256: 56EFDF808877BD88323499E4739AAB5F2C351521588336DFDBE35E75935C370A
  AppsAndFeaturesEntries:
  - DisplayName: SEZOY
    Publisher: TekDT
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
